### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by AFvladimir** [lily940703/fide#1]
I successfully ran the simulation. But then I tried to run the usage example it gave me this error: 

`Error in UseMethod("forecast") :    no applicable method for 'forecast' applied to an object of class "HoltWinters"`

It happens in this part:

```
for (i in 1:length(dataset_train_example)) {
  dataset_train_example[[i]] = calculate_forec_point(dataset_train_example[[i]])
}
```

Maybe you can help fix this issue?

**Comment by lily940703** [comment]
Thank you for posting this concern. This issue may be caused by a naming conflict, because the 'forecast' function exists in multiple packages. I've modified the code as follows. 
```
ses = HoltWinters(AS, beta = F, gamma = F)
fore = forecast::forecast(ses, h = h, level = level)
```
